# Project Configuration

# Data
data_root: 'data'  # Root directory for the dataset
train_dir: 'train'
val_dir: 'val'
test_dir: 'test'
image_size: 224    # Image size for resizing

# Model
model_name: 'swin_base_patch4_window7_224'  # Swin Transformer model name from timm
pretrained: True   # Use pretrained weights (ImageNet)
num_classes: 2     # Real or Fake

# Training
batch_size: 32
num_epochs: 3
learning_rate: 0.00001
optimizer: 'Adam'
loss_function: 'CrossEntropyLoss'

# Augmentations
train_augmentations:
  - name: 'HorizontalFlip'
    p: 0.5
  - name: 'ShiftScaleRotate'
    p: 0.3
  - name: 'RandomBrightnessContrast'
    p: 0.3
  - name: 'ColorJitter'
    p: 0.3
  # Add more augmentations as needed

val_augmentations:
  # Typically fewer or no augmentations for validation

# Logging and Checkpointing
log_dir: 'logs'
checkpoint_dir: 'checkpoints'
save_top_k: 3     # Save top k models based on validation performance

# Other
seed: 42
num_workers: 16    # Number of dataloader workers
